# inputs.conf – Splunk Universal Forwarder (Windows Agent)
# Location: C:\Program Files\SplunkUniversalForwarder\etc\system\local\inputs.conf

[WinEventLog://Application]
index = wineventlog
disabled = 0

[WinEventLog://Security]
index = wineventlog
disabled = 0
whitelist = 4624,4625,4634,4648,4672,4698,4720,4732

[WinEventLog://System]
index = wineventlog
disabled = 0

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
index = sysmon
disabled = 0
renderXml = true
